apiVersion: v1
kind: Secret
metadata:
  name: okta-oidc-testapp1
type: Opaque
data:
  clientId: MG9hczZyZmVwYVN4QWYySDc1ZDc=
  clientSecret: eXdlZkdKTmpwaW5jamFrQ2wyc1lwTnM5R2ZkZ3d6c3hWLTFqLTAtNXhBd09KNGpJRDBYelJtUHNXdVNqYXJtSg==
  secret: S1lYYUc3b1dob0g3QmowRTV6bDY1emxIWEMxU3dTTHo=
