apiVersion: v1
kind: Secret
metadata:
  name: okta-oidc-testapp1
type: Opaque
stringData:
  clientId: 0oascuazveDyhJog55d7
  clientSecret: Kju_0FO2ChjCrv8RqfAyoGvkMKU2bzc0zqrY67zaHWUqDwahPVY85VhoiX5VbuAJ
  secret: SEIaWeyyIWkuuShU7xrw9VVJ85kpzbtm

---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth2-testapp2
type: Opaque
stringData:
  clientId: Ov23likkmGvZFtmix4VU
  clientSecret: 621b46ba3057cae529f7851207033f0f34947721
  secret: G0fl1jjdvfGFFz9Theq4GRwFU42yQQ5x
